# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shbdeviceidentifier/rpc/proto/devices_database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shbdeviceidentifier/rpc/proto/devices_database.proto',
  package='SmartHomeBuddy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n4shbdeviceidentifier/rpc/proto/devices_database.proto\x12\x0eSmartHomeBuddy\"@\n\x0fIdentifyRequest\x12\x18\n\x10\x63lassifier_model\x18\x01 \x01(\t\x12\x13\n\x0bmeasurement\x18\x02 \x01(\t\"\x12\n\x10IdentifyResponse2g\n\x0f\x44\x65vicesDatabase\x12T\n\x0fIdentifyDevices\x12\x1f.SmartHomeBuddy.IdentifyRequest\x1a .SmartHomeBuddy.IdentifyResponseb\x06proto3')
)




_IDENTIFYREQUEST = _descriptor.Descriptor(
  name='IdentifyRequest',
  full_name='SmartHomeBuddy.IdentifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classifier_model', full_name='SmartHomeBuddy.IdentifyRequest.classifier_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='measurement', full_name='SmartHomeBuddy.IdentifyRequest.measurement', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=136,
)


_IDENTIFYRESPONSE = _descriptor.Descriptor(
  name='IdentifyResponse',
  full_name='SmartHomeBuddy.IdentifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['IdentifyRequest'] = _IDENTIFYREQUEST
DESCRIPTOR.message_types_by_name['IdentifyResponse'] = _IDENTIFYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentifyRequest = _reflection.GeneratedProtocolMessageType('IdentifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFYREQUEST,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.IdentifyRequest)
  ))
_sym_db.RegisterMessage(IdentifyRequest)

IdentifyResponse = _reflection.GeneratedProtocolMessageType('IdentifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFYRESPONSE,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.IdentifyResponse)
  ))
_sym_db.RegisterMessage(IdentifyResponse)



_DEVICESDATABASE = _descriptor.ServiceDescriptor(
  name='DevicesDatabase',
  full_name='SmartHomeBuddy.DevicesDatabase',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=158,
  serialized_end=261,
  methods=[
  _descriptor.MethodDescriptor(
    name='IdentifyDevices',
    full_name='SmartHomeBuddy.DevicesDatabase.IdentifyDevices',
    index=0,
    containing_service=None,
    input_type=_IDENTIFYREQUEST,
    output_type=_IDENTIFYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICESDATABASE)

DESCRIPTOR.services_by_name['DevicesDatabase'] = _DEVICESDATABASE

# @@protoc_insertion_point(module_scope)
