# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shbdeviceidentifier/rpc/proto/devices_database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shbdeviceidentifier/rpc/proto/devices_database.proto',
  package='SmartHomeBuddy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n4shbdeviceidentifier/rpc/proto/devices_database.proto\x12\x0eSmartHomeBuddy\" \n\x0f\x43lassifyRequest\x12\r\n\x05param\x18\x01 \x01(\t\"#\n\x10\x43lassifyResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\"\x1f\n\x0e\x44\x65vicesRequest\x12\r\n\x05param\x18\x01 \x01(\t\"+\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x02 \x01(\t\"2\n\x07\x44\x65vices\x12\'\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x16.SmartHomeBuddy.Device2\xb1\x01\n\x0f\x44\x65vicesDatabase\x12T\n\x0f\x43lassifyDevices\x12\x1f.SmartHomeBuddy.ClassifyRequest\x1a .SmartHomeBuddy.ClassifyResponse\x12H\n\rGetAllDevices\x12\x1e.SmartHomeBuddy.DevicesRequest\x1a\x17.SmartHomeBuddy.Devicesb\x06proto3')
)




_CLASSIFYREQUEST = _descriptor.Descriptor(
  name='ClassifyRequest',
  full_name='SmartHomeBuddy.ClassifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='SmartHomeBuddy.ClassifyRequest.param', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=104,
)


_CLASSIFYRESPONSE = _descriptor.Descriptor(
  name='ClassifyResponse',
  full_name='SmartHomeBuddy.ClassifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_done', full_name='SmartHomeBuddy.ClassifyResponse.is_done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=141,
)


_DEVICESREQUEST = _descriptor.Descriptor(
  name='DevicesRequest',
  full_name='SmartHomeBuddy.DevicesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='SmartHomeBuddy.DevicesRequest.param', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=174,
)


_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='SmartHomeBuddy.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SmartHomeBuddy.Device.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac_address', full_name='SmartHomeBuddy.Device.mac_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=219,
)


_DEVICES = _descriptor.Descriptor(
  name='Devices',
  full_name='SmartHomeBuddy.Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='SmartHomeBuddy.Devices.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=271,
)

_DEVICES.fields_by_name['devices'].message_type = _DEVICE
DESCRIPTOR.message_types_by_name['ClassifyRequest'] = _CLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['ClassifyResponse'] = _CLASSIFYRESPONSE
DESCRIPTOR.message_types_by_name['DevicesRequest'] = _DEVICESREQUEST
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['Devices'] = _DEVICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassifyRequest = _reflection.GeneratedProtocolMessageType('ClassifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYREQUEST,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.ClassifyRequest)
  ))
_sym_db.RegisterMessage(ClassifyRequest)

ClassifyResponse = _reflection.GeneratedProtocolMessageType('ClassifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESPONSE,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.ClassifyResponse)
  ))
_sym_db.RegisterMessage(ClassifyResponse)

DevicesRequest = _reflection.GeneratedProtocolMessageType('DevicesRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEVICESREQUEST,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.DevicesRequest)
  ))
_sym_db.RegisterMessage(DevicesRequest)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.Device)
  ))
_sym_db.RegisterMessage(Device)

Devices = _reflection.GeneratedProtocolMessageType('Devices', (_message.Message,), dict(
  DESCRIPTOR = _DEVICES,
  __module__ = 'shbdeviceidentifier.rpc.proto.devices_database_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.Devices)
  ))
_sym_db.RegisterMessage(Devices)



_DEVICESDATABASE = _descriptor.ServiceDescriptor(
  name='DevicesDatabase',
  full_name='SmartHomeBuddy.DevicesDatabase',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=274,
  serialized_end=451,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClassifyDevices',
    full_name='SmartHomeBuddy.DevicesDatabase.ClassifyDevices',
    index=0,
    containing_service=None,
    input_type=_CLASSIFYREQUEST,
    output_type=_CLASSIFYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllDevices',
    full_name='SmartHomeBuddy.DevicesDatabase.GetAllDevices',
    index=1,
    containing_service=None,
    input_type=_DEVICESREQUEST,
    output_type=_DEVICES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICESDATABASE)

DESCRIPTOR.services_by_name['DevicesDatabase'] = _DEVICESDATABASE

# @@protoc_insertion_point(module_scope)
