# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from shbdeviceidentifier.rpc.proto import heartbeat_pb2 as shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2


class HeartbeatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHeartbeat = channel.unary_unary(
                '/Heartbeat/GetHeartbeat',
                request_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2.HeartbeatResponse.FromString,
                )


class HeartbeatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HeartbeatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeartbeat,
                    request_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2.HeartbeatRequest.FromString,
                    response_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Heartbeat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Heartbeat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Heartbeat/GetHeartbeat',
            shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2.HeartbeatRequest.SerializeToString,
            shbdeviceidentifier_dot_rpc_dot_proto_dot_heartbeat__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
