# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shbdeviceidentifier.rpc.proto import pcap_database_pb2 as shbdeviceidentifier_dot_rpc_dot_proto_dot_pcap__database__pb2


class PcapDatabaseStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadPcapIntoDatabase = channel.unary_unary(
        '/SmartHomeBuddy.PcapDatabase/LoadPcapIntoDatabase',
        request_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_pcap__database__pb2.DbLoadRequest.SerializeToString,
        response_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_pcap__database__pb2.DbLoadResponse.FromString,
        )


class PcapDatabaseServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadPcapIntoDatabase(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PcapDatabaseServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadPcapIntoDatabase': grpc.unary_unary_rpc_method_handler(
          servicer.LoadPcapIntoDatabase,
          request_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_pcap__database__pb2.DbLoadRequest.FromString,
          response_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_pcap__database__pb2.DbLoadResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SmartHomeBuddy.PcapDatabase', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
