# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shbdeviceidentifier/rpc/proto/pcap_database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shbdeviceidentifier/rpc/proto/pcap_database.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n1shbdeviceidentifier/rpc/proto/pcap_database.proto\"5\n\rDbLoadRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x11\n\tfile_type\x18\x02 \x01(\t\"!\n\x0e\x44\x62LoadResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\x32G\n\x0cPcapDatabase\x12\x37\n\x14LoadPcapIntoDatabase\x12\x0e.DbLoadRequest\x1a\x0f.DbLoadResponseb\x06proto3')
)




_DBLOADREQUEST = _descriptor.Descriptor(
  name='DbLoadRequest',
  full_name='DbLoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='DbLoadRequest.file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_type', full_name='DbLoadRequest.file_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=106,
)


_DBLOADRESPONSE = _descriptor.Descriptor(
  name='DbLoadResponse',
  full_name='DbLoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_done', full_name='DbLoadResponse.is_done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['DbLoadRequest'] = _DBLOADREQUEST
DESCRIPTOR.message_types_by_name['DbLoadResponse'] = _DBLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbLoadRequest = _reflection.GeneratedProtocolMessageType('DbLoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _DBLOADREQUEST,
  __module__ = 'shbdeviceidentifier.rpc.proto.pcap_database_pb2'
  # @@protoc_insertion_point(class_scope:DbLoadRequest)
  ))
_sym_db.RegisterMessage(DbLoadRequest)

DbLoadResponse = _reflection.GeneratedProtocolMessageType('DbLoadResponse', (_message.Message,), dict(
  DESCRIPTOR = _DBLOADRESPONSE,
  __module__ = 'shbdeviceidentifier.rpc.proto.pcap_database_pb2'
  # @@protoc_insertion_point(class_scope:DbLoadResponse)
  ))
_sym_db.RegisterMessage(DbLoadResponse)



_PCAPDATABASE = _descriptor.ServiceDescriptor(
  name='PcapDatabase',
  full_name='PcapDatabase',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=143,
  serialized_end=214,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadPcapIntoDatabase',
    full_name='PcapDatabase.LoadPcapIntoDatabase',
    index=0,
    containing_service=None,
    input_type=_DBLOADREQUEST,
    output_type=_DBLOADRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PCAPDATABASE)

DESCRIPTOR.services_by_name['PcapDatabase'] = _PCAPDATABASE

# @@protoc_insertion_point(module_scope)
