# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shbdeviceidentifier.rpc.proto import read_pb2 as shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2


class ReadServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.read = channel.unary_unary(
        '/SmartHomeBuddy.ReadService/read',
        request_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.ReadRequest.SerializeToString,
        response_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.ReadResponse.FromString,
        )
    self.updateReadStatus = channel.unary_unary(
        '/SmartHomeBuddy.ReadService/updateReadStatus',
        request_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.UpdateReadStatusRequest.SerializeToString,
        response_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.UpdateReadStatusResponse.FromString,
        )


class ReadServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def read(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateReadStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReadServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'read': grpc.unary_unary_rpc_method_handler(
          servicer.read,
          request_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.ReadRequest.FromString,
          response_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.ReadResponse.SerializeToString,
      ),
      'updateReadStatus': grpc.unary_unary_rpc_method_handler(
          servicer.updateReadStatus,
          request_deserializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.UpdateReadStatusRequest.FromString,
          response_serializer=shbdeviceidentifier_dot_rpc_dot_proto_dot_read__pb2.UpdateReadStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SmartHomeBuddy.ReadService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
