# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shbdeviceidentifier/rpc/proto/read.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shbdeviceidentifier/rpc/proto/read.proto',
  package='SmartHomeBuddy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(shbdeviceidentifier/rpc/proto/read.proto\x12\x0eSmartHomeBuddy\"(\n\x0bReadRequest\x12\x19\n\x11\x63\x61pture_file_path\x18\x01 \x01(\t\"\x1f\n\x0cReadResponse\x12\x0f\n\x07is_done\x18\x01 \x01(\x08\"+\n\x17UpdateReadStatusRequest\x12\x10\n\x08progress\x18\x01 \x01(\x05\"\x1a\n\x18UpdateReadStatusResponse2\xb7\x01\n\x0bReadService\x12\x41\n\x04Read\x12\x1b.SmartHomeBuddy.ReadRequest\x1a\x1c.SmartHomeBuddy.ReadResponse\x12\x65\n\x10UpdateReadStatus\x12\'.SmartHomeBuddy.UpdateReadStatusRequest\x1a(.SmartHomeBuddy.UpdateReadStatusResponseb\x06proto3')
)




_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='SmartHomeBuddy.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_file_path', full_name='SmartHomeBuddy.ReadRequest.capture_file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=100,
)


_READRESPONSE = _descriptor.Descriptor(
  name='ReadResponse',
  full_name='SmartHomeBuddy.ReadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_done', full_name='SmartHomeBuddy.ReadResponse.is_done', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=133,
)


_UPDATEREADSTATUSREQUEST = _descriptor.Descriptor(
  name='UpdateReadStatusRequest',
  full_name='SmartHomeBuddy.UpdateReadStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='SmartHomeBuddy.UpdateReadStatusRequest.progress', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=178,
)


_UPDATEREADSTATUSRESPONSE = _descriptor.Descriptor(
  name='UpdateReadStatusResponse',
  full_name='SmartHomeBuddy.UpdateReadStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['ReadResponse'] = _READRESPONSE
DESCRIPTOR.message_types_by_name['UpdateReadStatusRequest'] = _UPDATEREADSTATUSREQUEST
DESCRIPTOR.message_types_by_name['UpdateReadStatusResponse'] = _UPDATEREADSTATUSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), dict(
  DESCRIPTOR = _READREQUEST,
  __module__ = 'shbdeviceidentifier.rpc.proto.read_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.ReadRequest)
  ))
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), dict(
  DESCRIPTOR = _READRESPONSE,
  __module__ = 'shbdeviceidentifier.rpc.proto.read_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.ReadResponse)
  ))
_sym_db.RegisterMessage(ReadResponse)

UpdateReadStatusRequest = _reflection.GeneratedProtocolMessageType('UpdateReadStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREADSTATUSREQUEST,
  __module__ = 'shbdeviceidentifier.rpc.proto.read_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.UpdateReadStatusRequest)
  ))
_sym_db.RegisterMessage(UpdateReadStatusRequest)

UpdateReadStatusResponse = _reflection.GeneratedProtocolMessageType('UpdateReadStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEREADSTATUSRESPONSE,
  __module__ = 'shbdeviceidentifier.rpc.proto.read_pb2'
  # @@protoc_insertion_point(class_scope:SmartHomeBuddy.UpdateReadStatusResponse)
  ))
_sym_db.RegisterMessage(UpdateReadStatusResponse)



_READSERVICE = _descriptor.ServiceDescriptor(
  name='ReadService',
  full_name='SmartHomeBuddy.ReadService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=209,
  serialized_end=392,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='SmartHomeBuddy.ReadService.Read',
    index=0,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_READRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateReadStatus',
    full_name='SmartHomeBuddy.ReadService.UpdateReadStatus',
    index=1,
    containing_service=None,
    input_type=_UPDATEREADSTATUSREQUEST,
    output_type=_UPDATEREADSTATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_READSERVICE)

DESCRIPTOR.services_by_name['ReadService'] = _READSERVICE

# @@protoc_insertion_point(module_scope)
