name: '🔍 Codacy Analysis'

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        description: 'An authentication token for the Codacy API.'
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: Bandit, Prospector, Pylint, PMD CPD, Radon
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
