name: '🔍 Codacy Analysis'

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        description: 'An authentication token for the Codacy API.'
        required: true

jobs:
  codacy:
    runs-on: ubuntu-latest
    continue-on-error: true

    # Steps for the tools: Bandit, Prospector, Pylint, PMD CPD, Radon
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Bandit
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: Bandit
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647

      - name: Prospector
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: Prospector
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647

      - name: Pylint
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: Pylint
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647

      - name: PMD CPD
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: PMD CPD
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647

#      # Radon is not supported by the GitHub action (yet?), even though it is listed as a client side tool on
#      # https://docs.codacy.com/getting-started/supported-languages-and-tools/
#      - name: Radon
#        uses: codacy/codacy-analysis-cli-action@master
#        with:
#          tool: Radon
#          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
#          upload: true
#          max-allowed-issues: 2147483647
