name: '🔍 Codacy Analysis'

on:
  workflow_call:
    inputs:
      secret-token:
        description: 'The authentication token for codacy.'
        required: true
        type: string

jobs:
  review:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: Bandit, Prospector, Pylint, PMD CPD, Radon
          project-token: ${{ inputs.secret-token }}
          upload: true
          max-allowed-issues: 2147483647
