name: Build
on:
  push:
    branches: [ main, develop, workflows ]

jobs:
  prepare:
    uses: ./.github/workflows/_prepare.yml

  format:
    uses: ./.github/workflows/_format.yml

  review:
    needs: [ format ]
    uses: ./.github/workflows/_format.yml

  test:
    needs: [ prepare ]
    uses: ./.github/workflows/_unit_tests.yml

  build:
    needs: [ prepare, lint_and_format ]
    uses: ./.github/workflows/_build.yml
