name: Build
on:
  push:
    branches: [main, develop]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./electron-app
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run make
