name: Build
on:
  push:
    branches: [main, develop]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: cd electron-app && \
             npm ci
      - name: build
        run: cd electron-app && \
             npm make
