name: Build
on:
  push:
    branches: [main, develop]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./electron-app
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../device-identifier/requirements.txt
      - name: Build Python distributable for ${{ matrix.os }}
        run: |
          cd ../device-identifier
          pyinstaller cli.py
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - name: Install nodeJS dependencies
        run: npm ci
      - name: Build SmartHomeBuddy for ${{ matrix.os }}
        run: npm run make
