name: Format Code

on:
  pull_request:
    branches: [main, develop]
  push:

jobs:
  format-python-with-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 99"
          src: "./backend"
  format-electron-app-with-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          #prettier_options: --write **/*.{js,md} # TODO