name: Test
on:
  push:
    branches: [ main, develop, workflows ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      INFLUXDB_URL: https://dl.influxdata.com/influxdb/releases
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
        node: [ 16 ]
        include:
          - os: ubuntu-22.04
            os_family: Linux
            influxdb_version: influxdb2-2.3.0-linux-amd64
            influxdb_client_version: influxdb2-client-2.3.0-linux-amd64
            influxdb_unarchived_name: influxdb2_linux_amd64
          - os: windows-latest
            os_family: Windows
            influxdb_version: influxdb2-2.3.0-windows-amd64
            influxdb_client_version: influxdb2-client-2.3.0-windows-amd64
            influxdb_unarchived_name: influxdb2_windows_amd64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r device-identifier/requirements.txt
      - name: Install testing packages
        run: pip install pytest pytest-cov pytest-loguru
      - name: Build Python distributable for ${{ matrix.os }}
        run: |
          cd device-identifier
          pyinstaller device_identifier_server.py
      - name: Set Linux Environment Variables
        if: ${{ matrix.os_family == 'Linux'}}
        run: |
          echo "influxdb_archive=${{ matrix.influxdb_version }}.tar.gz" >> $GITHUB_ENV          
          echo "influxdb_client_archive=${{ matrix.influxdb_client_version }}.tar.gz" >> $GITHUB_ENV
      - name: Set Windows Environment Variables
        if: ${{ matrix.os_family == 'Windows'}}
        run: |
          echo "influxdb_archive=${{ matrix.influxdb_version }}.zip" >> $GITHUB_ENV          
          echo "influxdb_client_archive=${{ matrix.influxdb_client_version }}.zip" >> $GITHUB_ENV
      - name: Set Derived Environment Variables
        run: |
          echo "influxdb_full_url=${{ env.INFLUXDB_URL }}/${{ env.influxdb_archive }}" >> $GITHUB_ENV
          echo "influxdb_client_full_url=${{ env.INFLUXDB_URL }}/${{ env.influxdb_client_archive }}" >> $GITHUB_ENV
      - name: Get InfluxDB and Client
        run: |
          mkdir -p InfluxData/influxdb
          curl --remote-name --silent ${{ env.influxdb_full_url}}
          mkdir -p InfluxData/influxdb-client
          curl --remote-name --silent ${{ env.influxdb_client_full_url }}
      - name: Unpack InfluxDB on Linux
        if: ${{ matrix.os_family == 'Linux'}}
        run: |
          tar xzvf ${{ env.influxdb_archive }}          
          tar xzvf ${{ env.influxdb_client_archive }}
      - name: Unpack InfluxDB on Windows
        if: ${{ matrix.os_family == 'Windows'}}
        run: |
          unzip ${{ env.influxdb_archive }}          
          unzip ${{ env.influxdb_client_archive }}
      - name: Move InfluxDB Files
        run: |
          mv ${{ matrix.influxdb_unarchived_name }}/* InfluxData/influxdb
          mv ${{ matrix.influxdb_client_version }}/* InfluxData/influxdb-client
          ls -la
          ls -la InfluxData/influxdb
      - name: Test with pytest
        run: |
          pytest device-identifier/tests --doctest-modules --junitxml=junit/test-results.xml --cov=shbdeviceidentifier --cov-report=xml --cov-report=html